
export const TOGGLE_NAV_BETWEEN_CONTENT_LESSON = "TOGGLE_NAV_BETWEEN_CONTENT_LESSON"
export const SET_TABLE_ROW_DETAILS = "SET_TABLE_ROW_DETAILS"
export const RESET_TABLE_ROW_DETAILS = "RESET_TABLE_ROW_DETAILS"